version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"  # Map your local port to the container's port
    depends_on:
      - db
    volumes:
      - .:/var/www/html

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"  # Map your local port to the container's port
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:


